@echo off
echo [*] Deleting old pyttsx3 MP3s to force complete Neural TTS regeneration...
if exist mp3\*.mp3 del /Q mp3\*.mp3
echo [*] Starting Edge-TTS Neural generation for all PDFs...
call run_audiobook.bat all
